# -*- coding: utf-8 -*-
"""task_2_2_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168BbJHE6Wn_wZQfXyijRZOVKJJvGm-zW
"""

def greetings(A):
  return('Доброго времени суток,', A[0], '"Человек"', A[1], '!')