# -*- coding: utf-8 -*-
"""task_2_2_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQ7ZsQVJFvrEzxfKC5EPq0ccKq0v0R2Q
"""

def debug_control(*args, **kwargs):
  return(len(args) + len(kwargs))